config/routes.rb
Rails.application.routes.draw do
  resources :breeds

  root "breeds#index"

end

app/models/breed.rb
class Breed < ActiveRecord::Base
  validates_presence_of :name, :pic_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  before_action :load_breed_list

  def index
    @breed = DogBreedFetcher.fetch
  end

  def show
    @breed = DogBreedFetcher.fetch(breed_name)
    render :index
  end

  private

  def load_breed_list
    @breeds = BreedListFetcher.fetch
  end

  def breed_name
    name = params[:id].to_s.split("--").join("/")
    name.blank? ? "random" : name
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/views/breeds/index.html.erb
<div class="container">
  <ul class="breeds">
    <% @breeds.each do |key, value| %>
      <li>
        <%= link_to key, breed_path(key) %>
        <% unless value.blank? %>
          <ul class="sub-breeds">
            <% value.each do |value_item| %>
              <li>
                <%= link_to value_item, breed_path("#{key}--#{value_item}") %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div class="dog">

    <h1>It's a dog</h1>

    <h3><%= @breed.name.humanize %></h3>

    <%= image_tag @breed.pic_url %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTestProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>